/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../lib/ng2-nvd3.module';
import * as import2 from '@angular/core/src/di/injector';
class NvD3ModuleInjector extends import0.NgModuleInjector<import1.NvD3Module> {
  _NvD3Module_0:import1.NvD3Module;
  constructor(parent:import2.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  createInternal():import1.NvD3Module {
    this._NvD3Module_0 = new import1.NvD3Module();
    return this._NvD3Module_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.NvD3Module)) { return this._NvD3Module_0; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const NvD3ModuleNgFactory:import0.NgModuleFactory<import1.NvD3Module> = new import0.NgModuleFactory(NvD3ModuleInjector,import1.NvD3Module);